index.md, server.py, server_classes.py
Also increased anon concurrent requests and allows for future expanding individual user concurrency
=> Added Working Prompt Queue Stats

server.py, server_classes.py
* Switch to redis for limiter storage
* A user and server management endpoints
* Added maintenance mode
* limiter now correctly handles foreign IPs
=> Management

horde/routes.py
Since the horde is growing in popularity, I figured I'd add some basic CSS to help make the page easier to read on mobile/tablet devices. See screenshots:
**Before (mobile):**
**After (mobile):**
---
**Before (desktop):**
**After (desktop):**
=> Add minimal styling to homepage, use mobile device scaling

horde/routes.py
🤦 this should work now. tested locally.
=> Fix broken style tag on homepage

README.md
=> spelling, etc.

CHANGELOG.md, FAQ.md, README_KoboldAIHorde.md, README_StableHorde.md, cli_logger.py, horde/apis/exceptions.py, horde/flask.py, horde/limiter.py, horde/routes.py, index_kobold.md, index_stable.md
Title says it all, just some minor typo fixes
=> Typos and Minor Documention Corrections

horde/bridge_reference.py
Add bridge capabilities of [sd-webui stable horde worker bridge](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker)
The version `2` for the `tiling` feature was actually not implemented on our side, but I would work on it in the next days, so I write it here first.
=> feat: add bridge capability of sd-webui bridge

horde/apis/models/v2.py, horde/apis/v2/base.py, horde/classes/base/team.py, horde/classes/base/user.py, horde/classes/kobold/worker.py, horde/database/functions.py, horde/database/text_functions.py, horde/model_reference.py
- Fixed a couple of cases of `{e}` not referring to a variable (missing `Exception as e`)
- Fixed a few cases of missing `self.` for variables or a `self` arg in a class method
- Removed a duplicated dictionary entry in `models\v2.py`.
- Fixed adding a team, which currently broken (500 and it doesn't work) due to a missing import, probably missed because it would have required a circular reference (`database\functions.py` logically required `base\team.py` and vice versa).
=> bug fixes post kaimerge

horde/apis/models/stable_v2.py, horde/bridge_reference.py
Code exists in nataili for this, just needs horde and worker to pass the parameter through
=> Add parameter to allow skipping the ControlNet preprocessor

horde/apis/models/stable_v2.py
PR's for AI-Horde-Worker, and Nataili coming soon once tested
=> New parameter to allow people to tweak the strength of the facefixers

horde/apis/models/stable_v2.py, horde/apis/v2/stable.py, horde/classes/stable/waiting_prompt.py
Adds 'return_control_map' for ControlNet, adds new post-processor 'strip_background`, and a suggested tweak to the kudos calculation
=> Add new parameters and adjust kudos calculations

horde/apis/models/stable_v2.py, horde/apis/models/v2.py, horde/apis/v2/stable.py, horde/bridge_reference.py, horde/classes/stable/genstats.py, horde/classes/stable/worker.py, horde/database/functions.py, horde/database/text_functions.py
=> LoRa support

horde/countermeasures.py
=> Fix typo in countermeasures.py

server.py
Dynamic loading of dotenv files based on OS environment variables
=> Dynamic loading of dotenv files based on OS environment variables

README_StableHorde.md
This PR fixes some grammar / spelling that I found in the `README_StableHorde.md` file.
=> fix: Grammer & spelling in readme

horde/apis/models/kobold_v2.py, horde/apis/models/stable_v2.py, horde/apis/models/v2.py
Thanks @Fripe070 for pointing the issue out
=> docs: fix dry_run api doc descriptions

horde/apis/models/kobold_v2.py
Kobold API standards for Dynatemp have been confirmed with @LostRuins and @AlpinDale on the KoboldAI discord 
PR contains lines to add Horde support
=> Add Dynatemp Support

.github/workflows/prtests.yml, requirements.dev.txt
This will fix the mixup with the PRs being based on main (and the workflow concurrency also being based on that).
=> ci: basis of PRs now PR'd branch

index_stable.md
- reformats text gen app section to match image gen section
- adds inneal to text gen app section
- capitalizes Aislingeach in the image gen app section
- adds Horde NG to image gen section
- removes AAAI UI and AI Brush, replaces with Horde NG and AI Scribbles
- I felt these were most active and updated clients that deserve to be mentioned over the other two
=> Add Inneal & Other Index Updates

CHANGELOG.md, horde/apis/models/stable_v2.py, horde/classes/stable/processing_generation.py, horde/consts.py
=> feat: Adds new information metadata
