horde/limiter.py
This adds three headers for rate limited routes after a limit occurs: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, and `X-RateLimit-Reset`
=> add ratelimit headers

horde/apis/models/stable_v2.py
Adding a flag for embeds so users can turn on/off whether the images are generated with embeds or not - plan is to have the workers load up the sd-concepts-library on start, and then at generation time, if the flag is checked, compare the prompt with db_embeds.json (that catalogs the library in the same way db.json does for models), and if it exists, check that embed's baseline matches the baseline of the model, and if so load the embed for the generation.
=> Add flag for embeds

index_stable.md
The author of the plugin asked for this here: https://github.com/benrugg/AI-Render/pull/68
Could this be added?
=> Add Blender Plugin to Plugins list on index page

horde/classes/stable/worker.py
See #158.
This (very small) change would update the endpoints which return worker details (including https://stablehorde.net/api/v2/workers) to show each (or the one) worker's ability to post process, aiding front ends in determining if a given request is possible under current horde conditions.
=> add 'allow_post_processing' to worker get_details()

horde/bridge_reference.py
It is not implemented currently, but in the plan.
Question: `r2_source` means that the `source_image` in the response JSON when the user using img2img would be an HTTP link rather than a base64 string?
=> feat: add feature references for sd-webui-bridge

horde/apis/models/kobold_v2.py
Max temp should be higher than 1.0, causes errors as current limit is too low.
=> fix bad maximum temperature for KAI

horde/bridge_reference.py, horde/classes/stable/worker.py
https://github.com/jug-dev/hordelib/pull/18, supports `image_is_control` again, which will be available on [bridge version 23](https://github.com/Haidra-Org/AI-Horde-Worker/pull/262).
=> fix: correctly assign `image_is_control` to bridge v23

horde/apis/models/stable_v2.py
TLDR: Sets the LoRa `clip` weight constraints to match the `model` weight constraints.
Hordelib 1.6.2 already supports negative `model`/`clip` strengths for LoRas. The current range is `(-5, 5)` for model strength on the API, but the clip strength range is `(0, 5)`. Hordelib will dutifully use a clip strength as low as -10 (a limit imposed by comfyui), but to minimize potentially wasteful results (-10 invariably destroys the image), I am recommending only that we bring the `clip` and `model` strength values in line with each other.
=> fix: allow negative LoRa clip strength

horde/classes/base/user.py
In an epic moment of variable name confusion, I failed to introduce the behavior I intended in the prior PR.
=> fix: shared key limit func now checks correct variable for `None`

horde/apis/v2/base.py
Fixes a bug in the shared key PATCH endpoint, and as @amiantos pointed out, it being a truthy check is faulty given valid values of some of those fields.
I am following their recommendation in the following way: 
```python
no_valid_actions = self.args.expiry is None and self.args.kudos is None and self.args.name is None
no_valid_limit_actions = self.args.max_image_pixels is None and self.args.max_image_steps is None and self.args.max_text_tokens is None
if no_valid_actions and no_valid_limit_actions:
raise e.NoValidActions("No shared key modification selected!")
```
=> fix: shared key patch endpoint typo corrected

horde/apis/v2/stable.py
To accommodate the state of the alpha/beta `reGen` worker's capabilities regarding SDXL.
=> fix: SDXL alpha/beta constraints

horde/apis/models/kobold_v2.py, horde/apis/v2/kobold.py
This commit finally adds support for the `stop_sequence` parameter for the text generation payload in Horde. The `stop_sequence` is an array of stopping strings that indicates to the backend when generation should be prematurely halted. As it is already integrated into Kobold as part of the submitted payload, no modification to the scribe/worker should be necessary. 
Do review, thanks!
=> This commit adds support for the stop_sequence parameter

horde/classes/base/processing_generation.py
This will help minimize the amount of extracting and client-side relating of messages in the logs. This will make it easier for me to investigate a user at glance without having to download and parse the logs.
=> feat: show requesting user in log on job submit

horde/apis/models/stable_v2.py
Following up on the [discussion in discord](https://discord.com/channels/781145214752129095/1182918213567270952/1183480524354900028):
- The LCM LoRa, and probably other features/model formats, work best with low (0.0-1.0) CFG scales.
- Presently, the horde only allows CFG scales [which are multiples of 0.5.](https://github.com/Haidra-Org/AI-Horde/blob/2155d4866c5b1ef72c2280fdadc378499aecae5a/horde/apis/models/stable_v2.py#L64)
- I suspect this current state of affairs is rooted in a time when a different backend for inference was being used, as there is no technical reason to require values divisible by 0.5 for ComfyUI right now.  
- This change allows the CFG scale to include precision down to 0.01.
=> feat: support cfg scales to 0.01 precision

horde/exceptions.py
Changes abuse timeout warnings to be less specific (by not specifying the time left of the ban) for anything more than a 4-day timeout.
=> fix: don't show long abuse timeout durations

horde/apis/models/stable_v2.py, horde/apis/v2/stable.py
Due to the field being a floating point number, and the flask mechanism not adequately supporting `multiple` for that datatype for our purposes, I have [removed the constraint from the API model](https://github.com/Haidra-Org/AI-Horde/blob/c3988aa106aeabdba8ac99de70cda737c77098b6/horde/apis/models/stable_v2.py#L64) and [added a simple rounding check](https://github.com/Haidra-Org/AI-Horde/blob/c3988aa106aeabdba8ac99de70cda737c77098b6/horde/apis/v2/stable.py#L159C29-L159C29) which should give the intended behavior for floating point values which are sent/represented as greater than 2 decimals.
=> fix: handle cfg_scale precision w/o changing datatype

horde/apis/models/stable_v2.py
The API docs for LoRa usage show `GlowingRunesAIV6` currently as an example. This LoRa was deleted and readded under a different name and as such is now invalid as a value currently. This PR updates the value to one uploaded by @db0 (Magnagothica) and slightly clarifies the API doc field description.
This will also resolve https://github.com/Haidra-Org/horde-sdk/issues/119 as a consequence (automatically; the SDK issue is due to the test payloads/responses relying on the API docs to mock this field) after this change is live and the next SDK release happens.
Thanks @daveschumaker for pointing this out.
=> fix: show working lora example

.github/workflows/maintests.yml, .gitignore, horde/apis/models/v2.py, horde/classes/base/processing_generation.py, horde/database/threads.py, horde/exceptions.py, horde/flask.py, horde/model_reference.py, horde/patreon.py, requirements.dev.txt, requirements.txt, tests/conftest.py, tests/test_alchemy.py, tests/test_image.py, tests/test_text.py
This PR creates a GitHub workflow that instantiates a functional AI-Horde and runs the already available (but tweaked in this PR) pytest-compliant tests in the `AI-Horde/tests/` folder and also checks formatting and linting rules. Additionally, this workflow downloads the latest *published* (on pypi) [horde_sdk](https://github.com/Haidra-Org/horde-sdk) and runs certain tests from `horde_sdk` against this test AI-Horde instance.
The following [repository secrets](https://github.com/Haidra-Org/AI-Horde/settings/secrets/actions) will need to be configured for this workflow to work:
```
R2_TRANSIENT_ACCOUNT # S3/R2 endpoint (IE https://xyzxyz.r2.cloudflarestorage.com)
R2_PERMANENT_ACCOUNT # S3/R2 endpoint (IE https://xyzxyz.r2.cloudflarestorage.com)
SHARED_AWS_ACCESS_ID # S3/R2 ID …
```
=> ci: preliminary ci support

.github/workflows/prtests.yml
This PR will introduce the repository behavior of allowing the CI to run on PRs **if, and only if** the PR itself is labeled with the github label `allow-ci`.
Note that without this extra layer of protection, arbitrary code could potentially be run using the secrets in this repository. Presently, the CI only runs on push to main. This PR's approach still isn't quite perfect but so long as the label is only applied to known (trusted) parties' PRs, this should be safe enough.
=> ci: support for CI on whitelisted PRs 

horde/database/functions.py
This will allow the `/v2/status/models/{model_name}` endpoint to support forward slashes in the model name, as is common for text models. For example, `aphrodite%2FNeverSleep%2FNoromaid-13b-v0.3` will become `aphrodite/NeverSleep/Noromaid-13b-v0.3`.
=> fix: parse url escaped values for model names

horde/apis/models/kobold_v2.py, horde/apis/models/v2.py, horde/apis/v2/base.py, horde/classes/base/user.py, requirements.dev.txt
In the course of expanding the SDK, certain inconsistencies were made apparent. This PR serves to correct the issues.
- [fix: use SinglePeriodTxtStat for text totals stat endpoint](https://github.com/Haidra-Org/AI-Horde/pull/403/commits/f291061949b32db60d66d04361d2eb86ac9a2f1a)
- Previously, probably due to copy and pasting, the `/v2/stats/text/totals` endpoint published in the swagger doc that returned elements were of type `SinglePeriodImgStat`, which could be a source of confusion when consuming the swagger doc. `/v2/stats/img/totals` returns elements with different attributes, so this PR hopefully will clarify that the two endpoints return two different types of objects.
- [fix: set min_length for image attr in ExtraSourceImage](https://github.com/Haidra-Org/AI-Horde/pull/403/commits/6 …
=> fix: Various API model fixes

horde/apis/models/kobold_v2.py
This corrects the API doc for the text async generate endpoint.
=> fix: use the correct response model for text async

.github/workflows/prtests.yml
This fixes the problem where the required-label-job would race with the actual test.
=> tests: run pr actions sequentially

horde/apis/apiv2.py, horde/flask.py
what I really wanted was to enable deep linking support, but swagger-restx doesn't support it.
https://github.com/python-restx/flask-restx/issues/518
=> expand api docs by default

horde/apis/v2/kobold.py, horde/apis/v2/stable.py, horde/classes/__init__.py, horde/classes/base/user.py, horde/classes/kobold/genstats.py, horde/classes/stable/genstats.py, horde/classes/stable/known_image_models.py, horde/database/__init__.py, horde/database/threads.py, horde/model_reference.py, sql_statements/README.md, sql_statements/cron/schedule_cron_job.sql, sql_statements/stored_procedures/compile_imagegen_stats_models.sql, sql_statements/stored_procedures/compile_imagegen_stats_totals.sql, sql_statements/stored_procedures/compile_textgen_stats_models.sql, sql_statements/stored_procedures/compile_textgen_stats_totals.sql, sql_statements/stored_procedures/cron_jobs/cron_stats.sql
Being victims of our own success, the increase in the size of the stats tables has led to the `/stats/*` endpoints becoming slower and slower over time. To remedy this, I've introduced some new tables, new stored procedures, and [pg_cron](https://github.com/citusdata/pg_cron) into the mix so these endpoints are always precomputed and that the backends have fewer long-running threads. See the `sql_statements/README.md` for some additional information.
This also creates the `known_image_models` table which is populated with the entries from the [model reference](https://github.com/Haidra-Org/AI-Horde-image-model-reference/stable_diffusion.json). This serves to allow us to one day refactor the `model_reference` shared module object out in preference for this table.
=> feat: caching improvements for stats endpoints

.github/workflows/maintests.yml, .github/workflows/prtests.yml, horde/apis/v2/base.py
- As found in the new [haidra-docker-images](https://github.com/Haidra-Org/haidra-docker-images) repo, the postgres service container is now a custom haidra-org authored one. 
- Currently, the only difference from the official postgres image is the [installation](https://github.com/Haidra-Org/haidra-docker-images/blob/main/ai-horde/postgres/Dockerfile) and [configuration](https://github.com/Haidra-Org/haidra-docker-images/blob/main/ai-horde/postgres/init_pg_cron.sql) of [pg_cron](https://github.com/citusdata/pg_cron). However, by having this new repo, we can easily modify the database image in the future and it makes it available to developers for local purposes or even possible third-party horde deployers.
- The lint/format check now happens in a parallel job so the substance of the code …
=> tests: use postgres container w/ pg_cron; lint checking now happens in its own job

horde/classes/base/worker.py, horde/database/functions.py
- The worker check-in fix would come up very rarely in production but was presenting a challenge for local development and for the CI runner. 
- It was incidentally noted that certain keys were unset (and unsent) from the skipped dict when they didn't apply and for consistency and completeness we're going to initialize them to 0 instead.
=> fix: new workers now check in more reliably; fix: more `skipped` keys to 0 instead of null

horde/classes/kobold/genstats.py, horde/classes/stable/genstats.py, sql_statements/cron/schedule_cron_job.sql
- Running `UPDATE cron.job SET nodename = '';` allows pg_cron to operate as expected. Without it, there is connection problem when the scheduled job attempts to run.
- `created` is a now appropriately accounted for and only the latest compiled stats for the compiled 'models stats' are returned in the relevant queries.
=> fix: stats not updating; 'latest' compiled stats not used

horde/classes/base/user.py
Previous to this change, users with `public_workers: true` would also broadcast this information. I am assuming this was an oversight and not intended.
=> fix: only broadcast `active_generations` for self or admin

horde/apis/v2/base.py
Users with max_sharedkeys == 3 could create 4 shared keys.
This does not affect already created shared keys, just prohibits creations of new keys when user is at the limit.
=> Fix off-by-one in create shared keys

horde/apis/v2/base.py, horde/classes/base/user.py, horde/database/functions.py, horde/horde_redis.py
Redis cache is now refreshed when User is modified.
After creating or deleting a shared key, it is not immediately reflected on `/get_user` endpoint as it serves now stale cached version.
This adds functionality to bust the user cache - both by id and by api_key - ensuring the cached results are always fresh.
1. call `GET /api/v2/find_user`, you should see `[]` under `sharedkey_ids`
2. call `GET /api/v2/users/:user_id`, you should see `[]` under `sharedkey_ids`
3. call `PUT /api/v2/sharedkeys` with body `{}`
4. call `GET /api/v2/find_user` again, you should see `['5d81849a...']` under `sharedkey_ids`
5. call `GET /api/v2/users/:user_id` again, you should also see `['5d81849a...']` under `sharedkey_ids`
6. call `DELETE /api/v2/sharedkeys/:keyId`
7. call `GET /api/v2/find_user`, you should …
=> Refresh User cache when user is modified

horde/classes/base/worker.py
the docs explicitly say that the IP address is privileged, and don't mention it being made available based on public_worker field.
If the user wants to make their contact info public, they can include it in the info field
- there's an argument for a flag to make this available to other users as well (or even to make it available only to trusted workers), but I'm not picky here.
This issue was noticed by Sidorok [here](https://discord.com/channels/781145214752129095/1034314422912565288/1309661916989358100)
This fix is untested (I'm doing this from my tablet)
=> Keep worker IP addresses and user contact info private when public_worker settings allow unprivileged requests to browse a user's workers

horde/classes/kobold/processing_generation.py
Once upon a time, before batching and other optimizations, these were the speeds we considered unreasonable but new paradigms, backends and breakthroughs have made these numbers increasingly inaccurate or irrelevant.
While I do think there has to be some sort of longer term solution (such as the one addressing the problem detailed in https://github.com/Haidra-Org/AI-Horde/issues/463), there have been virtually *only* false positives, and the few true positives boiled down to innocent misconfigurations.
Further, it appears that certain types of worker-reported failures can artificially inflate token count, which may be its own issue.
For the time being, I am advocating that the number is increased to 100t/s for most models, as recommended by henky, and that we respond to possible abuse of …
=> fix: token suspicion adjustment

horde/apis/v2/kobold.py, horde/apis/v2/stable.py
- because `self.params` is being set as a reference to `self.existing_style.params`, changes to `self.params` below (like width, height, n) end up being saved to the style when `self.existing_style.use_count` is updated and saved to the database. Copying the `self.existing_style.params` dictionary with `copy.deepcopy()` will ensure that `self.params` is a unique dictionary and is not in any way referencing the `self.existing_style` object's `params` dictionary and its contents.
=> Fix: Horde Style Params Get Overwritten By User Provided Params

horde/classes/base/worker.py
Fixes #480
From a brief scan, this is my best guess at the source of the HTTP 500 when sending a payload containing `"team": ""` in a `PUT /api/v2/workers/{worker id}`. `set_team()` is called with the value `None` in a couple places, where it looks to me to be expecting an object with an `id` variable - so `set_team()` tries to access the instance variable `.id` within the value `None`, which I believe would throw an error(?).
This change skips the dot accessor if the argument was `None` and just assigns `None` directly to the field instead.
Careful review requested! 🙏 I don't speak snek and I'm not familiar with SQLAlchemy. I also have yet to set up a development environment for AI Horde so I have not tested this change - but I'll get on the dev env over the weekend, if not before.
=> fix: Unset worker team_id
